adding mask to hide credit card number
webjump/braspagpagador-sdk-adapter pull request #2
Opened 2018-05-31 05:43 UTC by jonataswebjump

2018-05-31 21:24 UTC, rodrigowebjump requested changes

2018-05-31 21:24 UTC, rodrigowebjump commented on Factories/LoggerFactoryInterface.php
> +	public static function make($message);
Fix indentation.

2018-05-31 21:24 UTC, rodrigowebjump commented on Factories/LoggerFactory.php
> +            '"creditCard":{"cardNumber":"************$2","holder":$3,"expirationDate":"$4","securityCode":"***","saveCard":"$6","brand":$7}',
Replace by checking all string at once for me not looks like a safety way. If one fails, no one will be replaced.
I think that should be one replace per time (array) in one call or another most effective and guaranteed way.

2018-06-01 01:14 UTC, jonataswebjump commented on Factories/LoggerFactoryInterface.php
> +	public static function make($message);
Done.

2018-06-01 01:14 UTC, jonataswebjump commented on Factories/LoggerFactory.php
> +            '"creditCard":{"cardNumber":"************$2","holder":$3,"expirationDate":"$4","securityCode":"***","saveCard":"$6","brand":$7}',
Done on last commit. Please review again.

2018-06-04 13:48 UTC, leandro-rosa approved these changes

2018-06-04 13:48 UTC, merged